# Generated by Django 3.2.8 on 2021-11-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caracteristica', models.TextField()),
                ('porte_do_animal', models.CharField(choices=[('P', 'Pequeno'), ('M', 'Medio'), ('G', 'Grande')], max_length=1)),
                ('especie_do_animal', models.CharField(choices=[('GT', 'Gato'), ('CH', 'Cachorro'), ('PS', 'Passaro')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banho', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1)),
                ('tosa', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1)),
            ],
        ),
    ]
